name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Pront greetig
        run: echo "Hello World!"
      - name: Proint goodbye
        run: echo "Done - bye!"
